Fix compilation error: include debugger_tracing.h in debugger.h
The StepFilterType enum is defined in debugger_tracing.h, so we need to
include that header in debugger.h to use it in the function declarations.